
mybatis:
  type-aliases-package: com.fanxb.backservice.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: dev
  application:
    name: psn-back-service
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 500ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 500ms
        max-idle: 8
        min-idle: 0
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/psn?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 123456
      #配置初始化大小，最小，最大
      initial-size: 2
      min-idle: 2
      max-active: 20
      #获取连接等待超时时间
      max-wait: 500
      #间隔多久检测一次需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000

  # flyway配置
  flyway:
    baseline-on-migrate: true
  # 邮件配置
  mail:
    host:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          port: 465
server:
  port: 8082
  servlet:
    context-path: /psn/api

# 小程序id和密钥，通过命令行参数传递
wx:
  appId:
  secret:

#debug: true